name: flutter_movie_ui_practice
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod:
  flutter_hooks: 
  hooks_riverpod:
  
  # Hive
  hive:
  hive_flutter: 
  
  # managing app informations
  flutter_launcher_icons:
  package_info_plus: 

  # assets
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # code generation
  build_runner: 
  
  hive_generator: 
  riverpod_generator: 
  riverpod_lint: 
  freezed:


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/movies/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
